package GUI;

import com.jtattoo.plaf.mcwin.McWinLookAndFeel;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import org.web3j.protocol.Web3j;
import org.web3j.protocol.core.methods.response.EthSendTransaction;
import org.web3j.protocol.http.HttpService;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author sbr
 */
public class SenderSign extends javax.swing.JFrame {

    /**
     * Creates new form SenderSign
     */
    public SenderSign() {
        initComponents();
        java.net.URL url = ClassLoader.getSystemResource("resources/images/satoshiturk.png");
        if (url != null) {
            Toolkit kit = Toolkit.getDefaultToolkit();
            Image img = kit.createImage(url);
            setIconImage(img);
        } else {
            System.out.println("İkon dosyası bulunamadı.");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        signtext = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        logtext = new javax.swing.JTextArea();
        signrpcurl = new javax.swing.JTextField();

        setTitle("SatoshiTURK HD Wallet");
        setAlwaysOnTop(true);
        setResizable(false);

        signtext.setColumns(20);
        signtext.setLineWrap(true);
        signtext.setRows(5);
        signtext.setWrapStyleWord(true);
        signtext.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Paste your signature below and click the send button, this process is irreversible.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 0, 0))); // NOI18N
        jScrollPane1.setViewportView(signtext);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("SEND");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        logtext.setColumns(20);
        logtext.setLineWrap(true);
        logtext.setRows(5);
        logtext.setWrapStyleWord(true);
        logtext.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Result", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 0, 0))); // NOI18N
        jScrollPane2.setViewportView(logtext);

        signrpcurl.setText("https://bsc-dataseed.binance.org/");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(signrpcurl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(336, 336, 336)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(376, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(signrpcurl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jScrollPane1, jScrollPane2});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        sendSignedTransaction();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            // JTattoo Look and Feel tema ayarı
            UIManager.setLookAndFeel(new McWinLookAndFeel());
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SenderSign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SenderSign().setVisible(true);
            }
        });
    }

    private void sendSignedTransaction() {
        String rpcUrl = signrpcurl.getText();
        String signedTx = signtext.getText();

        if (signedTx.isEmpty()) {
            logtext.append("İmzalı işlem metni boş.\n");
            return;
        }

        try {
            // Web3j nesnesi oluştur
            Web3j web3j = Web3j.build(new HttpService(rpcUrl));

            // İmzalı işlemi gönder
            EthSendTransaction sendResponse = web3j.ethSendRawTransaction(signedTx).send();

            if (sendResponse.hasError()) {
                logtext.append("İşlem gönderimi hatası: " + sendResponse.getError().getMessage() + "\n");
            } else {
                String transactionHash = sendResponse.getTransactionHash();
                logtext.append("İşlem başarıyla gönderildi. İşlem hash: " + transactionHash + "\n");
            }
        } catch (Exception ex) {
            logtext.append("İşlem gönderimi sırasında hata oluştu: " + ex.getMessage() + "\n");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea logtext;
    private javax.swing.JTextField signrpcurl;
    public static javax.swing.JTextArea signtext;
    // End of variables declaration//GEN-END:variables
}
